// SPDX-License-Identifier: Apache-2.0
// Tiny test-local IDL for the parameterised smoke test.

module Smoke {
  @topic
  struct Ping {
    @key long  id;
    long       counter;
    string     text;
  };
};
